"""create initial LossGraph schema

Revision ID: 6839d4ce2397
Revises: 
Create Date: 2026-08-29 12:10:28.390236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6839d4ce2397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_code'), 'merchants', ['merchant_code'], unique=True)
    op.create_table('abuse_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('cluster_code', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('exposure_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_clusters_cluster_code'), 'abuse_clusters', ['cluster_code'], unique=True)
    op.create_index(op.f('ix_abuse_clusters_merchant_id'), 'abuse_clusters', ['merchant_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_hash', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_address_hash'), 'addresses', ['address_hash'], unique=True)
    op.create_index(op.f('ix_addresses_merchant_id'), 'addresses', ['merchant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_hash', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_hash'), 'devices', ['device_hash'], unique=True)
    op.create_index(op.f('ix_devices_merchant_id'), 'devices', ['merchant_id'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_ip_hash'), 'ip_addresses', ['ip_hash'], unique=True)
    op.create_index(op.f('ix_ip_addresses_merchant_id'), 'ip_addresses', ['merchant_id'], unique=False)
    op.create_table('payment_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_hash', sa.String(length=255), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_instruments_instrument_hash'), 'payment_instruments', ['instrument_hash'], unique=True)
    op.create_index(op.f('ix_payment_instruments_merchant_id'), 'payment_instruments', ['merchant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ip_address_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('payment_instrument_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_status', sa.String(length=50), nullable=True),
    sa.Column('chargeback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_instrument_id'], ['payment_instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_address_id'), 'transactions', ['address_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_ip_address_id'), 'transactions', ['ip_address_id'], unique=False)
    op.create_index('ix_transactions_merchant_created', 'transactions', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_instrument_id'), 'transactions', ['payment_instrument_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_code'), 'transactions', ['transaction_code'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_merchant_id'), 'audit_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_transaction_id'), 'audit_events', ['transaction_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('ml_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('graph_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('behavior_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_transaction_id'), 'risk_assessments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_transaction_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_audit_events_transaction_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_merchant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_transactions_transaction_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_instrument_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index('ix_transactions_merchant_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_address_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_address_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_instruments_merchant_id'), table_name='payment_instruments')
    op.drop_index(op.f('ix_payment_instruments_instrument_hash'), table_name='payment_instruments')
    op.drop_table('payment_instruments')
    op.drop_index(op.f('ix_ip_addresses_merchant_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_ip_hash'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_devices_merchant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_addresses_merchant_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address_hash'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_abuse_clusters_merchant_id'), table_name='abuse_clusters')
    op.drop_index(op.f('ix_abuse_clusters_cluster_code'), table_name='abuse_clusters')
    op.drop_table('abuse_clusters')
    op.drop_index(op.f('ix_merchants_merchant_code'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###